---
server:
  port: 7443

spring:
  profiles:
    active: dev
  application:
    name: cloud-auth
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
  client:
    default-to-properties: false