---
server:
  port: 80
spring:
  application:
    name: cloud-test
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
  client:
    default-to-properties: false